Patch floating bubble
youzan/vant pull request #11880
Opened 2023-05-18 13:47 UTC by zhousg

### 问题描述

close #11843 

### 效果演示

https://vant-git-patch-floating-bubble-zhousg.vercel.app/#/zh-CN/floating-bubble

2023-05-28 13:43 UTC, zhousg commented
@chenjiahan 有空可以查看下 😊

2023-06-03 07:58 UTC, zqran requested changes

2023-06-03 07:58 UTC, zqran commented on packages/vant/src/floating-bubble/README.md
> +# FloatingBubble 浮动气泡
```suggestion
# FloatingBubble
```

2023-06-03 07:58 UTC, zqran commented on packages/vant/src/floating-bubble/README.md
> +### 类型定义
```suggestion
### Types
```

2023-06-03 07:58 UTC, zqran commented on packages/vant/src/floating-bubble/README.md
> +      showToast('点击气泡');
```suggestion
      showToast('Some messages');
```

2023-06-03 08:03 UTC, zhousg commented
Thanks @zqran

2023-06-18 13:15 UTC, chenjiahan commented on packages/vant/src/floating-bubble/FloatingBubble.tsx
> +            <Icon name="chat" class={bem('icon')} />
可以提供一个 icon 属性来让用户设置这个图标

另外我倾向于不设置默认的 icon name，完全让用户来设置。因为 FloatingBubble 这个组件名称是中性的，没有 chat 的含义（否则就是 ChatBubble 了）

2023-06-18 13:15 UTC, chenjiahan commented on packages/vant/src/floating-bubble/FloatingBubble.tsx
> +export type OffsetType = {
组件向使用者导出的类型变量可以加个组件名前缀，比如 FloatingBubbleOffset

2023-06-18 13:15 UTC, chenjiahan commented on packages/vant/src/floating-bubble/README.zh-CN.md
> +| offset-change | 位置改变后触发 | _{x: string, y: string}_ |
可以描述地更准确一些

```suggestion
| offset-change | 由用户拖拽导致位置改变后触发 | _{x: string, y: string}_ |
```

2023-06-18 13:15 UTC, chenjiahan commented on packages/vant/src/floating-bubble/README.zh-CN.md
> +| teleport | 指定挂载的节点，<br> 等同于 Teleport 组件的 [to 属性](https://v3.cn.vuejs.org/api/built-in-components.html#teleport) | _string \| Element_ | `body` |
这里 Vue 的 URL 可以更新了哈，参考 https://github.com/youzan/vant/commit/8320eb1e1672c1c1abacd722114a2c0b4c05ed55

2023-06-18 13:15 UTC, chenjiahan commented on packages/vant/src/floating-bubble/README.zh-CN.md
> +| v-model:offset | 控制气泡位置 | _OffsetType_ | `{x: -1, y: -1}` |
默认值 -1 的含义似乎比较模糊，实际上使用者看到的默认值应该是右下角，而 -1 / -1 比较像是左上角

2023-06-18 13:15 UTC, chenjiahan commented on packages/vant/src/floating-bubble/FloatingBubble.tsx
> +    const updateState = async () => {
Vant 组件代码里目前是不使用 async / await 的哈，因为 async 在 Chrome >= 55 / iOS >= 11 才支持，降级 async 会引入很多胶水代码，让产物体积变大

我们为了保持轻量，就尽量不使用 async / await

2023-06-18 13:15 UTC, chenjiahan commented on packages/vant/src/floating-bubble/FloatingBubble.tsx
> +const { width: windowWidth, height: windowHeight } = useWindowSize();
可以直接从 utils 里导入 windowWidth / windowHeight，有一份默认的

2023-06-18 13:15 UTC, chenjiahan commented on packages/vant/src/floating-bubble/README.zh-CN.md
> +| space | 气泡与窗口的最小间距，单位为 `px` | _number_ | `24` |
把 space 命名成 gap 如何， "gap"则更常用于描述间距

2023-06-18 13:15 UTC, chenjiahan commented on packages/vant/src/floating-bubble/README.zh-CN.md
> +| space | 气泡与窗口的最小间距，单位为 `px` | _number_ | `24` |
另外我在想是不是可以允许对 x 和 y 轴分别定义间距

2023-06-18 13:16 UTC, chenjiahan commented
> 有空可以查看下 😊

sorry 拖延症犯了，来晚了😂

2023-06-18 13:18 UTC, chenjiahan commented on packages/vant/src/floating-bubble/demo/index.vue
> +    freeMagnetic: '自由磁吸',
```suggestion
    freeMagnetic: '自动磁吸',
```

2023-06-18 13:20 UTC, chenjiahan commented on packages/vant/src/floating-bubble/index.less
> +  border-radius: 50%;
这里可以用 --van-radius-max，因为 50% 在 width / height 不相同的情况下会有问题，比如 width: 200 / height 50 时会变成这个样子：

![image](https://github.com/youzan/vant/assets/7237365/9b696098-99b0-48a4-829e-a059fac2aa9d)

2023-06-18 13:21 UTC, chenjiahan commented on packages/vant/src/floating-bubble/README.zh-CN.md
> +| axis | 拖拽的方向，`xy` 代表自由拖拽 | _'x' \| 'y' \| 'xy'_ | `y` |
可以禁用拖拽吗

2023-06-18 13:22 UTC, chenjiahan commented on packages/vant/src/floating-bubble/index.less
> +  --van-floating-bubble-z-index: 9999;
9999 似乎太大了，会超过弹出层的 z-index，比如 Popup 啥的

2023-06-18 13:26 UTC, zhousg commented
> > 有空可以查看下 😊
> 
> sorry 拖延症犯了，来晚了😂

2023-06-18 13:29 UTC, zhousg commented
> > 有空可以查看下 😊
> 
> sorry 拖延症犯了，来晚了😂

💗 已经很高效了，周末还处理了很多 PR ，辛苦CR ☕️

2023-06-18 14:27 UTC, zhousg commented on packages/vant/src/floating-bubble/README.zh-CN.md
> +| space | 气泡与窗口的最小间距，单位为 `px` | _number_ | `24` |
还有一个 boundary 没有暴露，觉的如果要控制四周间距 boundary 它更灵活些

2023-06-18 14:34 UTC, zhousg commented on packages/vant/src/floating-bubble/README.zh-CN.md
> +| axis | 拖拽的方向，`xy` 代表自由拖拽 | _'x' \| 'y' \| 'xy'_ | `y` |
可以哈

2023-06-18 15:26 UTC, zhousg commented on packages/vant/src/floating-bubble/FloatingBubble.tsx
> +      moving = true;
如果点击条件放开了，可能出现小于 5px 的移动除了触发 click 还会触发  update:offset 和 offsetChange 事件，这种冲突可以接受吗

2023-06-18 15:38 UTC, inottn commented on packages/vant/src/floating-bubble/FloatingBubble.tsx
> +      moving = true;
我理解可能指 x 或 y 轴移动超过 TAP_OFFSET 时，视作触发移动，可以更新气泡位置，并触发对应事件。相反则触发 click 事件。

2023-06-18 15:39 UTC, inottn commented on packages/vant/src/floating-bubble/index.less
> +  --van-floating-bubble-z-index: 9999;
可以和 BackTop 组件保持一致

2023-06-18 16:13 UTC, zhousg commented on packages/vant/src/floating-bubble/FloatingBubble.tsx
> +      moving = true;
假设用户就是想移动 4px 呢？

2023-06-19 02:09 UTC, chenjiahan commented on packages/vant/src/floating-bubble/FloatingBubble.tsx
> +      moving = true;
> 假设用户就是想移动 4px 呢？

这种可以忽略哈，因为 4px 相当于 1% 的手机屏幕宽度，手指很难控制到这个精度

2023-06-19 02:10 UTC, chenjiahan commented on packages/vant/src/floating-bubble/README.zh-CN.md
> +| space | 气泡与窗口的最小间距，单位为 `px` | _number_ | `24` |
嗯嗯，可以先按目前的 gap: number 来提供，未来支持 gap 设置为对象（相当于暴露 boundary），`{ top: 'xx', left: 'xx', bottom: 'xx', right: 'xx' }` 这种

2023-06-19 03:25 UTC, zhousg commented on packages/vant/src/floating-bubble/FloatingBubble.tsx
> +      moving = true;
修改好了~

2023-06-21 09:54 UTC, inottn commented
good，现在可以使用 `touch.isTap` 复用相关逻辑了。

2023-06-21 09:59 UTC, inottn commented on packages/vant/src/floating-bubble/FloatingBubble.tsx
> +        touch.reset();
touch.start 中会执行 reset 操作，这里就可以省略了，因为 click 事件是在 touchend 之后触发的，reset 会将 isTap 的值也重置了。

2023-06-21 10:02 UTC, zhousg commented on packages/vant/src/floating-bubble/FloatingBubble.tsx
> +        touch.reset();
touch 的 isTap 我有疑问哈，如果移动了 4px 但是时间 1000ms 这个时候算  isTap 还是 move

2023-06-21 10:11 UTC, inottn commented on packages/vant/src/floating-bubble/FloatingBubble.tsx
> +        touch.reset();
算isTap，因为原生的 click 事件是不会考虑接触屏幕的时间的，这里 isTap 的逻辑是 cover 用户可能点击过程中产生的略微移动，所以只会考虑移动的距离。
其实我感觉 5px 也略微大了点，长按事件阈值 5px，点击可以在短一点点。

2023-06-21 10:17 UTC, zhousg commented on packages/vant/src/floating-bubble/FloatingBubble.tsx
> +        touch.reset();
> touch.start 中会执行 reset 操作，这里就可以省略了，因为 click 事件是在 touchend 之后触发的，reset 会将 isTap 的值也重置了。

不过这里有些特殊哈，isTap 的重置需要等 click 触发后再重置，默认用了 touch 的 isTap 是不是有影响呀？

2023-06-21 10:19 UTC, zhousg commented on packages/vant/src/floating-bubble/FloatingBubble.tsx
> +    const TAP_TIME = 250;
如果 click 不考虑时间的话，我移除了哈，我理解是 tap 事件了

2023-06-21 10:21 UTC, inottn commented on packages/vant/src/floating-bubble/FloatingBubble.tsx
> +        touch.reset();
会在下次 touchstart 里调用 `touch.start` 的时候重置。
touchstart(重置) -> touchmove -> touchend -> click -> touchstart(重置)

2023-06-21 10:40 UTC, zhousg commented
@inottn 改好了，isTap 👍🏻

2023-06-21 14:38 UTC, chenjiahan approved these changes

2023-06-21 14:38 UTC, merged

2023-06-21 14:38 UTC, chenjiahan commented
🎉🎉🎉